import logging
from sqlalchemy.orm import Session
from app.database import SessionLocal
from app.models.panel import Panel

logger = logging.getLogger(__name__)

def generate_kml_flightpath(farm_id: str, altitude: int = 20) -> str:
    """
    Generates a KML file containing a lawnmower flight path 
    across all panels in a farm at a specific altitude.
    """
    db: Session = SessionLocal()
    try:
        panels = db.query(Panel).filter(Panel.farm_id == farm_id).all()
        if not panels:
            return ""

        # Group panels by row
        rows = {}
        for p in panels:
            r = int(p.row_num)
            if r not in rows:
                rows[r] = []
            rows[r].append(p)

        # Sort rows
        sorted_row_nums = sorted(rows.keys())
        
        waypoints = []
        direction_left_to_right = True
        
        for r in sorted_row_nums:
            # Sort columns ascending or descending based on direction
            row_panels = sorted(rows[r], key=lambda x: int(x.col_num), reverse=not direction_left_to_right)
            for p in row_panels:
                waypoints.append(f"{p.lng},{p.lat},{altitude}")
            
            # Flip direction for the next row to create lawnmower pattern
            direction_left_to_right = not direction_left_to_right

        kml_coords = "\n          ".join(waypoints)
        
        kml = f"""<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
  <Document>
    <name>Flight Path for {farm_id}</name>
    <description>Automated lawnmower flight path generated by SolarShield</description>
    <Style id="yellowLineGreenPoly">
      <LineStyle>
        <color>7f00ffff</color>
        <width>4</width>
      </LineStyle>
      <PolyStyle>
        <color>7f00ff00</color>
      </PolyStyle>
    </Style>
    <Placemark>
      <name>Autonomous Flight Path</name>
      <styleUrl>#yellowLineGreenPoly</styleUrl>
      <LineString>
        <extrude>1</extrude>
        <tessellate>1</tessellate>
        <altitudeMode>relativeToGround</altitudeMode>
        <coordinates>
          {kml_coords}
        </coordinates>
      </LineString>
    </Placemark>
  </Document>
</kml>"""
        return kml
    except Exception as e:
        logger.exception("Failed to generate KML flight path")
        return ""
    finally:
        db.close()
