/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "on-primary-fixed": "#001d31",
              "on-tertiary-fixed": "#2d1600",
              "secondary-fixed": "#e0e3e5",
              "primary": "#006194",
              "on-tertiary-fixed-variant": "#6b3b00",
              "surface-container-highest": "#d8e3fb",
              "tertiary-fixed": "#ffdcc0",
              "on-secondary-container": "#626567",
              "outline-variant": "#bfc7d2",
              "on-surface": "#111c2d",
              "outline": "#707881",
              "surface-variant": "#d8e3fb",
              "tertiary-fixed-dim": "#ffb875",
              "on-error-container": "#93000a",
              "secondary-fixed-dim": "#c4c7c9",
              "tertiary-container": "#ac6200",
              "surface-tint": "#006398",
              "secondary-container": "#e0e3e5",
              "on-tertiary": "#ffffff",
              "error-container": "#ffdad6",
              "on-primary-fixed-variant": "#004b73",
              "on-surface-variant": "#3f4850",
              "on-secondary-fixed-variant": "#444749",
              "surface-bright": "#f9f9ff",
              "secondary": "#5c5f61",
              "primary-container": "#007bb9",
              "primary-fixed": "#cce5ff",
              "background": "#f9f9ff",
              "surface-container-lowest": "#ffffff",
              "on-primary-container": "#fdfcff",
              "inverse-primary": "#93ccff",
              "inverse-surface": "#263143",
              "surface": "#f9f9ff",
              "inverse-on-surface": "#ecf1ff",
              "on-background": "#111c2d",
              "on-primary": "#ffffff",
              "on-secondary": "#ffffff",
              "on-tertiary-container": "#fffbff",
              "on-secondary-fixed": "#191c1e",
              "surface-container-high": "#dee8ff",
              "on-error": "#ffffff",
              "tertiary": "#894d00",
              "surface-container-low": "#f0f3ff",
              "surface-dim": "#cfdaf2",
              "error": "#ba1a1a",
              "primary-fixed-dim": "#93ccff",
              "surface-container": "#e7eeff"
      },
      "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
      },
      "spacing": {
              "sm": "16px",
              "md": "24px",
              "xl": "64px",
              "margin-desktop": "32px",
              "base": "4px",
              "lg": "40px",
              "gutter": "24px",
              "margin-mobile": "16px",
              "xs": "8px"
      },
      "fontFamily": {
              "body-lg": ["Inter"],
              "label-md": ["Inter"],
              "headline-sm": ["Inter"],
              "headline-lg-mobile": ["Inter"],
              "headline-md": ["Inter"],
              "headline-lg": ["Inter"],
              "label-sm": ["Inter"],
              "body-sm": ["Inter"],
              "body-md": ["Inter"]
      },
      "fontSize": {
              "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
              "label-md": ["14px", {"lineHeight": "20px", "fontWeight": "500"}],
              "headline-sm": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
              "headline-lg-mobile": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
              "headline-md": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
              "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
              "label-sm": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}],
              "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
              "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}]
      }
    }
  }
}
